swagger: "2.0"
info:
  description: "Books API"
  version: "1.0.0"
  title: "Books API"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

host: "localhost"
basePath: "/v1"

tags:
- name: "books"
  description: "Managing books"

schemes:
- "http"

paths:
  /book:
    get:
      tags:
      - "book"
      summary: "Get all books"
      responses:
        200:
          description: "List of books"
          schema:
            type: array
            items:
              $ref: '#/definitions/BookDTO'
    post:
      tags:
      - "book"
      summary: "Add a new book"
      parameters:
      - in: "body"
        name: "body"
        description: "Book information"
        required: true
        schema:
          $ref: "#/definitions/BookDTO"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/BookDTO"
        405:
          description: "Invalid input"
  /book/{id}:
    get:
      tags:
      - "book"
      summary: "Find book by ID"
      description: "Returns a single book"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of book to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/BookDTO"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Book not found"

definitions:
  BookDTO:
    type: "object"
    required:
      - "author"
      - "title"
      - "published"
    properties:
      id:
        type: "integer"
        format: "int64"
      author:
        type: "string"
        minLength: 3
        maxLength: 255
      title:
        type: "string"
        minLength: 3
        maxLength: 255
      published:
        type: "string"
        format: "date"
      notes:
        type: "string"
